"""empty message

Revision ID: 0608f039d135
Revises: 49a7d13ade92
Create Date: 2024-03-28 17:36:33.604102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0608f039d135'
down_revision = '49a7d13ade92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
