"""empty message

Revision ID: 23725af8809f
Revises: 40cabfe6b17e
Create Date: 2024-03-27 21:55:37.216257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23725af8809f'
down_revision = '40cabfe6b17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_homeworld_id_fkey', type_='foreignkey')
        batch_op.drop_column('homeworld')
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('homeworld', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('character_homeworld_id_fkey', 'planet', ['homeworld_id'], ['id'])

    # ### end Alembic commands ###
